name: animal_rescue
description: Animal Rescue

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.0
  auto_route: ^7.9.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dartz: ^0.10.1
  uuid: ^4.3.3
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  injectable: ^2.4.0
  flutter_localizations:
    sdk: flutter
  firebase_core : ^2.3.0
  firebase_auth: ^4.17.9
  image_picker: ^1.0.7
  logger: ^2.2.0
  enum_annotation: ^0.0.4
  cloud_firestore: ^4.15.9
  firebase_storage: ^11.6.10
  path: ^1.9.0
  google_maps_flutter: ^2.6.0
  geolocator: ^11.0.0
  flutter_easyloading: ^3.0.5
  focus_detector: ^2.0.1
  fluttertoast: ^8.2.4
  dotted_border: ^2.1.0
  carousel_slider: ^4.2.1
  url_launcher: ^6.2.5
  geoflutterfire2: ^2.3.15
  custom_marker: ^1.0.0
  infinite_scroll_pagination: ^4.0.0
  intl_utils: ^2.8.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  auto_route_generator: ^7.3.2
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.1
  enum_generator: ^1.1.2
  injectable_generator: ^2.6.1

dependency_overrides:
  meta: ^1.12.0

flutter_gen:

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: false

  colors:
    inputs:
      - assets/colors/colors.xml

flutter:
  uses-material-design: true
  assets:
   - assets/icons/
   - assets/images/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/lato/Lato-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/lato/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/lato/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/lato/Lato-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/lato/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/lato/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/lato/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/lato/Lato-ThinItalic.ttf
          weight: 100
          style: italic
flutter_intl:
  enabled: true
  output_dir: lib/gen
